# platform :ios, '9.0'

workspace 'DGLogExample'

target 'iOS Example' do
  project 'iOS Example/iOS Example.xcodeproj'
  pod 'DGLog', :path => '../'

  use_frameworks!
end

target 'OSX Example' do
  project 'OSX Example/OSX Example.xcodeproj'
  pod 'DGLog', :path => '../'

  use_frameworks!
end
