workspace 'DGLogExample'

abstract_target 'DGLog' do

  pod 'DGLog', :path => '../'

  target 'iOS Example' do
    project 'iOS Example/iOS Example.xcodeproj'
    platform :ios, '8.0'
  
    pod 'DGLog', :path => '../', :testspecs => ['UnitTests', 'UITests'] 
  
    use_frameworks!
  end
  
  target 'OSX Example' do
    project 'OSX Example/OSX Example.xcodeproj'
    platform :osx, '10.14'
  
    pod 'DGLog', :path => '../', :testspecs => ['UnitTests', 'UITests'] 
  
    use_frameworks!
  end
  
end
